### ISSUE TITLE
chown2me.c seems to be vulnerable to symlink attacks (CWE-61)

### ISSUE THREAD

**Issue by robert-scheck** [scVENUS/PeekabooAV#1]
1. As random local user: `ln -s /etc/passwd /tmp/amavis-123`
2. Run `/opt/peekaboo/bin/chown2me` as `peekaboo:peekaboo`
3.  Ooops…file `/etc/passwd` belongs to `peekaboo:peekaboo`

Not sure what a proper fix could be, maybe `lchown()` rather `chown()`. Yes, systemd's `ProtectSystem` might help to prevent this – _if_ systemd is being used.

**Comment by Jack28** [comment]
Thanks
Fancy enough I guess. Enjoyed this bug

https://twitter.com/peekabooav/status/872953550174904327
