### ISSUE TITLE
Peekaboo causes Mail-Queue

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#10]
Hi Felix,
It's me again.
I adjusted the `$max_servers` value to `150`.  After that, when I relay an example domain to the peekaboo server, I get huge mailq. Even if the emails do not have any attachments it really takes very long until they pass the server.
I just tried to disable the peekabooav and used only amavisd. If only amavis is working it doesn't generate a mailq. Looks like i'm having timing issuses.  :-(
Do you have any ideas or tips?

regards, Michael

**Comment by Jack28** [comment]
There has been effects with lock downs of peekaboo in previous versions. Which version / code state do you use? The problem last existed verifiably before we started using SocketServer.

With a value of 150 for amavis there is 150 concurrent amavis process. Under high load that's up to 150 socket connections. Peekaboo then processes data provided by amavis in parallel (by sample). You can experiment with `worker_count` in `peekaboo.conf`
What is your current configured value for the number of Peekaboo Workers?

**Comment by MigliS** [comment]
Currently I'm still using peekaboo version 1.2.
My `worker_count` value is only at `3` at the moment. I'm going to examine with an increase of this value in the `peekaboo.conf`.
You'll hear from me.

**Comment by MigliS** [comment]
Do I also need to increase the `max_use` value in the `/etc/postfix/master.cf` to the same like amavis and peekaboo workers?

**Comment by Jack28** [comment]
If you experience connection drops and timeouts for incomming mail you might be able to tweak a bit here. I assume this value to be independent from Peekaboo and best set to your usual default.

A value of 150 might be a good starting point for `worker_count`

**Comment by Jack28** [comment]
This issue seems to be sorted.
If you still experience problems try configuring Peekaboo to use the cuckooprocessor wrapper
https://github.com/scVENUS/PeekabooAV-Installer/blob/master/cuckoo/cuckooprocessor.sh
that addresses performance issues and instabilities in Cuckoo
http://docs.cuckoosandbox.org/en/latest/usage/utilities/#processing-utility

Best
Felix
