### ISSUE TITLE
emotet-malware which is not recognized by cuckoo

### ISSUE THREAD

**Issue by thegrillmaster** [scVENUS/PeekabooAV#106]
[analyzer.txt](https://github.com/scVENUS/PeekabooAV/files/3715791/analyzer.txt)
[cuckoo.txt](https://github.com/scVENUS/PeekabooAV/files/3715793/cuckoo.txt)

Hello everyone, I know this post doesn't really belong here, but I can't get an answer in the official forum, so I'm asking you if you can help me here. I have here as an attachment an emotet Malware, which is not recognized by Cuckoo. Unfortunately I have no idea why not. Can you have a look and maybe give me a hint? Attention, the attachment is dangerous, the password is "infected".
Thank you very much for your support!

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Peekaboo1.7, Cuckoo 2.0.7, Ubuntu 18.04, Win7sp164x
[Anhang_Q-723-NGI3699.zip](https://github.com/scVENUS/PeekabooAV/files/3715762/Anhang_Q-723-NGI3699.zip)

**Comment by thegrillmaster** [comment]
[analyzer.txt](https://github.com/scVENUS/PeekabooAV/files/3715794/analyzer.txt)
[cuckoo.txt](https://github.com/scVENUS/PeekabooAV/files/3715795/cuckoo.txt)

**Comment by Jack28** [comment]
Note: we are talking about this file:
https://www.virustotal.com/gui/file/fb9952619f249f3185a0f56ffcca0d1ed3027fa8c924efc788d4b2100ea92b40

"40 engines detected this file"

**Comment by thegrillmaster** [comment]
If I have this analysed there, there will be this result:
https://sandbox.pikker.ee/analysis/1403422/summary

That's my problem. Cuckoo does not recognize that it contains macros and I have no plan why

**Comment by Jack28** [comment]
Yes, "Office document contains one or more macros (7 events)" but Cuckoo is not able to deobfuscate them.

The two performed HTTP requests are very suspicious since they point at some potentially hacked WordPress installations.

The HTTP requests don't deliver the payload. The first request returns a page with "<title>Suspected phishing site | Cloudflare</title>" and the second 302. So in this case no malicious action is performed because the infection/dropper fails.

What I can suggest is to use a new rule (that is not included in 1.7) called `office_macro_with_suspicious_keyword` to match on the `AutoOpen` keyword inside the macro. We use Oletools to statically check for suspicious keywords, configurable here:
https://github.com/scVENUS/PeekabooAV/blob/b3d21e8b689b5fe59335cfff99414d92d45aadb9/ruleset.conf.sample#L76

**Comment by Jack28** [comment]
Another possibility is to setup inetsim which also is in the most recent code base of the installer. Inetsim will then accept all requests and answer with a reply that fits the request. Because of the request being answered properly Cuckoo can gather more data and produce a better report.

**Comment by thegrillmaster** [comment]
Hello Jack, thank you so much for the answers. I implemented the first tip, but I won't be able to test it until next week. I thought Inetsim too. If it is already integrated in your code, is there a manual how to install and activate it? I didn't find anything about it. Thank you

**Comment by thegrillmaster** [comment]
Hello, Jack, another stupid question... wouldn't you be able to get a ready Virtualbox image with Amavis, Peekaboo and Cuckoo? That would be super ingenious, I could test with it whether something is wrong with my installation. According to me this would not violate any copyright. I would be very happy about that, maybe it will work :) Thanks a lot

**Comment by Clevero** [comment]
For the record: I can replicate this issue.

I have sometimes some word documents that do not execute properly, I think. To this time I couldn't find out why but in some cases the cuckoo agent throws an error like the screenshot below. Do you get the same error?
I was able to detect those word files nonetheless, but with URLs found during the analysis. If one of the URLs is on a specific list (URLs that are share malware) it will trigger a cuckoo signature that is declared as a bad signature in ruleset.conf

But I will dig into the main issue and report back. If you have any clues, would be happy to hear those!

While I went through your attached files I can see that the analysis did not completed successfully, instead the timeout is hit and cuckoo logs ```end of analysis reached!```
I had those errors too and @michaelweiser explained it a bit in a older issue:
```However, looking at your report I see message ``end of analysis reached!` which according to the Cuckoo source means that the analysis not only ran beyond the timeout but refused to be shut down by the agent and ran into the critical timeout as well at which point Cuckoo just shut down the VM. This IMO is a clear indicator of failure because analysis did indeed not finish and had to be aborted.```
https://github.com/scVENUS/PeekabooAV/issues/59#issuecomment-465222887

How does your setup look like? VirtualBox on a Ubuntu/Debian machine or in a virtualized enviorement?
My problem was that I had an Ubuntu VM on a vSphere cluster cluster running with Peekaboo and VirtualBox installed. So nested virtualization while vbox does not implementet it completly. With this setup often attachments did not execute properly or even word started correctly. 


![grafik](https://user-images.githubusercontent.com/6106081/66719547-ab65fd80-edf1-11e9-96db-9b5fd7f540d6.png)

**Comment by thegrillmaster** [comment]
Hello Clevero, I haven't noticed this mistake until now, but what you write may well be the problem. What irritates me very much is the fact that when I write this file at https://sandbox.pikker.ee, then the Yara-Rules will hit you there.
Yara 
Contains_VBA_macro_code - Detect a MS Office document with embedded VBA macro code
office_document_vba - Office document with embedded VBA

Or this one too:
Office document contains one or more macros (7 events)
macro_filename ThisDocument.cls macro_stream VBA/ThisDocument
macro_filename l1DdozU.cls macro_stream VBA/l1DdozU
macro_filename P3JMZ_Y.bas macro_stream VBA/P3JMZ_Y
macro_filename dTkkKJiJ.bas macro_stream VBA/dTkkKJiJ
macro_filename o6F85KDB.cls macro_stream VBA/o6F85KDB
macro_filename ntowNDG.bas macro_stream VBA/ntowNDG
macro_filename EE6Y9p8Z.bas macro_stream VBA/EE6Y9p8Z

These rules would have to strike even if there was no Inetsim? Unfortunately I don't see in the logs that the modules are worked through during the analysis, e.g. Yara, etc.
I hope we find a solution. 
As base system I use a Debian 10, Virtualbox 6, the analysis VM is a Ubuntu 18.04 with the PeekabooAV installation 1.7. To run the malware I use a Windows 7, SP1 64bit, Office 2010.

**Comment by thegrillmaster** [comment]
I have received an answer in the official forum... quite arrogant, but whatever.
"
pretty simple, cuckoo is opensource so here is work which  you need to do, to be able to detect everything, you can read docs and  write your own signatures

**Comment by thegrillmaster** [comment]
Meanwhile I could find a solution that detects the malware but is very slow because it needs a FullMemoryDump.
Here with this project:

https://medium.com/@soji256/build-a-malconfscan-with-cuckoo-environment-to-analyze-emotet-ff0c4c589afe

Now it would be interesting to integrate this repo into Peekaboo. Unfortunately scripting is not my field...
