### ISSUE TITLE
peekaboo.service: Start operation timed out. Terminating.

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#11]
Hi Felix,
Since wednesday, I'm not able to start the peekaboo.service via systemd. Unfortunately I can't figure out where the origin of this error is.
The problem doesn't occure if I start peekaboo with `/usr/bin/python /usr/bin/peekaboo -c peekaboo.conf`.
It should be possible to increase the timeout, I hope so.

Underlying you'll see my log file, which isn't really meaningful to me:
`Dec 01 08:21:11 hostname python[2215]: 2017-12-01 08:21:11,481 - peekaboo.daemon - (MainThread) - DEBUG - <PeekabooConfig({'db': {'url': 'postgresql://peekaboo:peekaboo@localhost:5432/peekaboo'}, 'global': {'job_hash_regex': '/var/spool/amavis/tmp/([^/]+)/parts.*', 'group': 'amavis', 'sample_base_dir': '/tmp', 'socket_file': '/var/run/peekaboo/peekaboo.sock', 'worker_count': '300', 'use_debug_module': 'yes', 'user': 'peekaboo', 'chown2me_exec': '/opt/peekaboo/bin/chown2me', 'pid_file': '/var/run/peekaboo/peekaboo.pid', 'interpreter': '/usr/bin/python'}, 'logging': {'log_format': '%(asctime)s - %(name)s - (%(threadName)s) - %(levelname)s - %(message)s', 'log_level': 'DEBUG'}, 'cuckoo': {'storage_path': '/opt/peekaboo/.cuckoo/storage', 'submit': '/usr/bin/cuckoo submit --unique', 'exec': '/usr/bin/cuckoo'}})>
Dec 01 08:22:35 hostname systemd[1]: peekaboo.service: Start operation timed out. Terminating.
Dec 01 08:22:35 hostname systemd[1]: Failed to start Peekaboo Extended Email Attachment Behavior Observation Owl.
Dec 01 08:22:35 hostname systemd[1]: peekaboo.service: Unit entered failed state.
Dec 01 08:22:35 hostname systemd[1]: peekaboo.service: Failed with result 'timeout'.
Dec 01 08:22:35 hostname systemd[1]: peekaboo.service: Service hold-off time over, scheduling restart.
Dec 01 08:22:35 hostname systemd[1]: Stopped Peekaboo Extended Email Attachment Behavior Observation Owl.
Dec 01 08:22:35 hostname systemd[1]: Starting Peekaboo Extended Email Attachment Behavior Observation Owl...
Dec 01 08:22:36 hostname python[6542]: PEEKABOO 1.3
Dec 01 08:22:36 hostname python[6542]: Peekaboo Extended Email Attachment Behavior Observation Owl`

regards, Michael

**Comment by Jack28** [comment]
Hi Michael,

you're right there is not much. Can you remember what changed to produce this behaviour? Was it when you upgraded to Peekaboo 1.3?
I'm sure you've tried to reboot your system ;-)

You can try to clean up Cuckoo, it has a built in command for that. It has happened to me that Cuckoo can not finish a job and tries again every time it is started.

Best
Felix

**Comment by MigliS** [comment]
Hi Felix,
The only thing I changes or added is a ramdisk. I think I'm having issues with the uid's & gid's. This could also be. On monday, I'm going to check if someone altered the users or smt else.

At the moment I'm getting the same error but with a few more information.

> Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Start operation timed out. Terminating.
_**Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Changed start -> final-sigterm
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Child 29448 belongs to peekaboo.service
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Main process exited, code=killed, status=15/TERM
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Changed final-sigterm -> failed
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Job peekaboo.service/start finished, result=failed**_
Dec 01 16:32:35 hostname systemd[1]: Failed to start Peekaboo Extended Email Attachment Behavior Observation Owl.
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Unit entered failed state.
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Failed with result 'timeout'.
_**Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Changed failed -> auto-restart
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: cgroup is empty
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Service hold-off time over, scheduling restart.
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Trying to enqueue job peekaboo.service/restart/fail
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Installed new job peekaboo.service/restart as 20384
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Enqueued job peekaboo.service/restart as 20384
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Scheduled restart job.
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Changed auto-restart -> dead
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Job peekaboo.service/restart finished, result=done
Dec 01 16:32:35 hostname systemd[1]: Stopped Peekaboo Extended Email Attachment Behavior Observation Owl.
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Converting job peekaboo.service/restart -> peekaboo.service/start
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: About to execute: /usr/bin/peekaboo -c /opt/peekaboo/peekaboo.conf
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Forked /usr/bin/peekaboo as 30098
Dec 01 16:32:35 hostname systemd[1]: peekaboo.service: Changed dead -> start**_
Dec 01 16:32:35 hostname systemd[1]: Starting Peekaboo Extended Email Attachment Behavior Observation Owl...
Dec 01 16:32:36 hostname systemd[30098]: peekaboo.service: Executing: /usr/bin/peekaboo -c /opt/peekaboo/peekaboo.conf

**Comment by MigliS** [comment]
Good morning Felix,
I now know where the timeout comes from. As far as I can see, the *.sock and *.pid file of peekaboo cannot be created.
I looked all config-files and permissions but I can't see where the problem is. These two files should be created in the directory `/var/run/peekaboo/` so I'm able to start the service via systemctl.

Any thoughts?
Michael

**Comment by Jack28** [comment]
From `peekaboo/daemon.py`  you can follow the steps that are performed before Peekaboo send the `systemd.notify("READY=1")`. Start from `main()` at the bottom, to `run()` and follow the code from there until line `196`. Increase `log_level` and check which parts are reached. 
Let me know what you find

**Comment by MigliS** [comment]
Okay I got one. I ran the command `python /opt/peekaboo/peekaboo/daemon.py --config /opt/peekaboo/peekaboo.conf`
![peekaboo_error_cuckoo](https://user-images.githubusercontent.com/12274029/33569207-36749bfa-d929-11e7-9be8-1b2af400ab22.JPG)
Seems like peekaboo is doing alright. :-)
But cuckoo has a weird error. Even though I'm in debug mode via systemd I don't get peekaboo.pjobs messages that the workers are ready.
![peekaboo_error_cuckoo2](https://user-images.githubusercontent.com/12274029/33569455-0fb8e7ea-d92a-11e7-89d4-2f2f4a0e7383.JPG)
Also `/usr/bin/cuckoo` should be fine.

**Just to say:** If I run peekaboo manually `python /usr/ bin/peekaboo -c /opt/peekaboo/peekaboo.conf` everything's fine. But there I'm getting a timeout if there's no input action. Then I need to restart peekaboo... It's a workaround but costs much time.

**Comment by Jack28** [comment]
There seems to be something wrong with the Cuckoo installation, try to reinstall Cuckoo, clean up local data and database and check if the error persists.

I expect the error to be present on manual run as well but it might not directly kill Peekaboo as opposed to the signal for systemd that's missing and makes systemd enter timeout and kill the cgroup.

**Comment by MigliS** [comment]
Could it also be the peekaboo database I'm using?
There I have over 50'000 entries, but postgresql should handle this. It's only a thought.

regards, 
Michael

**Comment by Jack28** [comment]
We're mostly using MariaDB but I haven't seen any problems with the database yet that could explain the behaviour you're experiencing.
Have you seen any improvements by reinstalling Cuckoo and clearing it's data?

**Comment by MigliS** [comment]
Issue can be closed.
Resolution: Clearing the Peekaboo Database solved the Problem. After restarting peekaboo, attachments could be analyzed again!
