### ISSUE TITLE
StopIteration Exception from pyparsing

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV#110]
With high load pyparsing runs into StopIteration Exceptions which quickly renders peekaboo unusable.

## Possible Solution
Remove Packrat Cache:
https://github.com/scVENUS/PeekabooAV/blob/778ff1931b793292c8fcdcc921dda76d92626524/peekaboo/ruleset/expressions.py#L454
Which should result in high performance loss.

## Steps to Reproduce
Send lots of jobs to peekaboo (version > 1.7)

## Context (Environment)
This is very likely because pyparsing is not thread safe
https://github.com/pyparsing/pyparsing/issues/89

## Possible Implementation
Expressions can be compiled only once and stored.

**Comment by michaelweiser** [comment]
Can reproduce with python 2.7.15~rc1-1 and pyparsing 2.2.0+dfsg1-2 on Ubuntu 18.04. Can not reproduce with python 3.6.7-1~18.04 same system same pyparsing version.
