### ISSUE TITLE
Submit error path broken

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV#122]
https://github.com/scVENUS/PeekabooAV/commit/1d1ba965a3cae3d46a76404707de1bfc8cd32d52 broke the submit error path so that requests starve if the database is unavailable. While it is correctly detected that the db is unavailable, it is no longer reported to the client that the sample could not be submitted and the connection is kept open indefinitely. I believe this is due to the fact that https://github.com/scVENUS/PeekabooAV/commit/1d1ba965a3cae3d46a76404707de1bfc8cd32d52#diff-fe25d3ca7f7ddc6f0228ca70f2f3a47fR177 correctly returns None but https://github.com/scVENUS/PeekabooAV/commit/1d1ba965a3cae3d46a76404707de1bfc8cd32d52#diff-fe25d3ca7f7ddc6f0228ca70f2f3a47fR211 unconditionally appends that None to ``submitted``, making it non-empty and thus non-false at https://github.com/scVENUS/PeekabooAV/blob/1d1ba965a3cae3d46a76404707de1bfc8cd32d52/peekaboo/server.py#L145.

**Comment by michaelweiser** [comment]
@Jack28: Do you concur? I can try to fix and perhaps improve the code a bit, if you agree.

**Comment by Jack28** [comment]
I agree 👍

**Comment by michaelweiser** [comment]
Will do. ;)
