### ISSUE TITLE
Alter Cuckoo Path in cuckoo.py ?

### ISSUE THREAD

**Issue by AMKpeacemaker** [scVENUS/PeekabooAV#14]
Ahoi,
I installed cuckoo in a different directory and have to start it with `--cwd /data/cuckoo `

because of that peekaboo is using a default configuration I assume and can't find my VMs.
My VMs have other names, cuckoo1 is the default name.

`2018-02-05 11:46:39,493 - peekaboo.toolbox.cuckoo - (MainThread) - DEBUG - STDERR 2018-02-05 11:46:39,493 [cuckoo.core.scheduler] INFO: Using "virtualbox" as machine manager
2018-02-05 11:46:39,830 - peekaboo.toolbox.cuckoo - (MainThread) - DEBUG - STDERR 2018-02-05 11:46:39,829 [cuckoo] CRITICAL: CuckooCriticalError: Please update your configuration. Unable to shut 'cuckoo1' down or find the machine in its proper state: The virtual machine 'cuckoo1' doesn't exist! Please create one or more Cuckoo analysis VMs and properly fill out the Cuckoo configuration!
2018-02-05 11:46:39,948 - peekaboo.toolbox.cuckoo - (MainThread) - WARNING - Cuckoo closed STDERR
`

Where can I change the path within peekaboo so it will use my Cuckoo-Conf-Files ?

Best regards
peacemaker

**Comment by Jack28** [comment]
Hi peacemaker,

thanks for your question.
At the moment it is not possible to configure a touple or list in `peekaboo.conf` for `exec` in the `[cuckoo]` config section as it is for `submit` (that is dues to limitations in how we call `twisted.internet.reactor` to run Cuckoo).

>  Cuckoo specific settings
> 
> [cuckoo]
> exec             :    /usr/local/bin/cuckoo
> submit           :    /usr/local/bin/cuckoo submit
> storage_path : /home/peekaboo/.cuckoo/storage

That will probably change as soon as we rebuild the interface to Cuckoo.

The solution for you right now would be to use a wrapper script similar to how it is set up by the PeekabooAV-Installer.

Have a look at this script: 
`github.com/scVENUS/PeekabooAV-Installer/cuckoo/cuckooprocessor.sh`
and the coresponding config (note the `interpreter` setting):
`github.com/scVENUS/PeekabooAV-Installer/peekaboo/peekaboo.conf`

Let me know or reopen if you still experience difficulties.

Best
Felix
