### ISSUE TITLE
"Peekaboo-Analysis av-scanner FAILED: CODE(0x5612b3c36680) unexpected ,"

### ISSUE THREAD

**Issue by Clevero** [scVENUS/PeekabooAV#17]
After installing with the great installer (Thanks! It makes the whole thing for me alot easier :D ), I get an error when submitting an example attachment.

**Steps to reproduce**
Sending an email with the tool swaks and putty.exe in the attachment

**Expected behavior**
Email is relayed with the original attachment since the attachment is just putty.

**Actual behaviour**
Mail is not relayed to the actual recipient. Admin is notfified, this mail states also: ```No viruses were found.```

Testing the file directly on the socket, like in the docs of the installer, the exe is not detected as harmful (in my understanding)
![grafik](https://user-images.githubusercontent.com/6106081/39124911-7558c872-46fd-11e8-838f-7bbf6b81af1d.png)

/var/log/mail.log:
```
Apr 23 14:31:22 peekaboo-debian amavis[8476]: (08476-01) (!)run_av (Peekaboo-Analysis) FAILED - unexpected , output="Hallo das ist Peekaboo\n\nDatei "p002" 4f81b422c9f73f4a6167267e03d3d51c76f894b12d500ff1fb1f8bfc249931d2 wird analysiert$
Apr 23 14:31:22 peekaboo-debian amavis[8476]: (08476-01) (!)Peekaboo-Analysis av-scanner FAILED: CODE(0x5612b3c36680) unexpected , output="Hallo das ist Peekaboo\n\nDatei "p002" 4f81b422c9f73f4a6167267e03d3d51c76f894b12d500ff1fb1f8bfc24$Apr 23 14:31:22 peekaboo-debian amavis[8476]: (08476-01) (!)...ingestuft\n\n" at (eval 99) line 951.
Apr 23 14:31:22 peekaboo-debian amavis[8476]: (08476-01) (!)WARN: all primary virus scanners failed, considering backups
Apr 23 14:31:22 peekaboo-debian amavis[8476]: (08476-01) (!!)AV: ALL VIRUS SCANNERS FAILED
Apr 23 14:31:23 peekaboo-debian amavis[8476]: (08476-01) Negative SMTP resp. to DATA: 554 5.5.1 Error: no valid recipients
Apr 23 14:31:23 peekaboo-debian amavis[8476]: (08476-01) (!)fipKy3OmPW8h(jvMoxGQxK759) SEND from <> -> <test@test.test>, ENVID=AM.fipKy3OmPW8h.20180423T123123Z@peekabooav-demo.int BODY=7BIT 454 4.7.1 from MTA(smtp:[192.168.56.1]:10025):$Apr 23 14:31:23 peekaboo-debian amavis[8476]: (08476-01) (!!)TROUBLE in check_mail: delivery-notification FAILED: temporarily unable to send DSN to <test@test.test>: 454 4.7.1 from MTA(smtp:[192.168.56.1]:10025): 454 4.7.1 <test@test.te$Apr 23 14:31:23 peekaboo-debian amavis[8476]: (08476-01) (!)PRESERVING EVIDENCE in /var/lib/amavis/tmp/amavis-20180423T143122-08476-bObvfHaH
```

Could someone please help me to solve my problem?

Hopefully, I did not something wrong while installing.

**Comment by Jack28** [comment]
Hi @Clevero,

sorry for the late reply. We've been taking care of quite a few things recently.

From what you say I assume the mailer daemon is not configured properly and amavis can't reach peekaboo.

- Check paths to the peekaboo socket file in the amavis and peekaboo configuration
- Try to connect via smtp to amavis (127.0.0.1:10024) and hand in your message there
- Check local mail delivery and try again

This way you test every step in the process and verify its correct and functional.


Regards
Felix

**Comment by Jack28** [comment]
Any news on this?

**Comment by Clevero** [comment]
@Jack28 Thank you for your response!

And I'm sorry that I did not answer yet.
The project at work was on hold and your messages have gone down in my mail inbox.
Currently, I'm trying to recreate the environment for Peekaboo in order to eliminate some other possible errors on my side.

Should I close this issue and reopen it if the problem persists with the new installations?

**Comment by Jack28** [comment]
Feel free to reopen.
Thanks
