### ISSUE TITLE
Question: Improve vm performance with linked clones

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#19]
Hi 

After a few consultations to improve the whole performance of our systems we want to let one vm running in the RAM and create linked copies, so it could run a bit faster. 
With our incoming traffic, specially in the morning and afternoon, peekaboo sometimes can't handle the mass and throttles down.
How did you implement this sceanario? As far as I know you need to have a dhcp-server running that cuckoo sandbox doesn't get ip conflicts... But we're not sure how to adjust the `<machinery>.conf`.

It would be very helpful to us.

Kind regards
Michael

**Comment by Jack28** [comment]
Hi Michael,

sorry it took us so long to get back to this. We have checked a few configurations and are currently operating with one VM that has linked clones so Linux core can figure out the base filesystem is user over and over again and keeps it in memory anyway.
We have a few scripts published with the installer to clone and snapshot VMs (https://github.com/scVENUS/PeekabooAV-Installer/tree/master/vm). You will see that we increment MAC addresses. Fairly straight forward.
It should also be easy to query `vboxmanage` for machine MAC addresses and create a config for e.g. `dnsmasq`.
Unless you change nameing schema or count of machines you should be fine with a static lets say `virtualbox.conf`.

I hope this helps you with the question. Please let me know if I got you wrong or if you've already come up with a better solution. And pls share your experience.

Best
Felix

**Comment by MigliS** [comment]
Hi Felix,

That's absolutely no problem.
I'm going to look at these scripts. Since we use KVM as our virtualization solution, I will take a closer look at this.
At the moment we are still working with individual machines and it seems that the system works perfectly with all the optimizations made.

You'll hear from me. :)

Kind regards
Michael

**Comment by michaelweiser** [comment]
Closing after one year of inactivity. Please reopen as necessary.
