### ISSUE TITLE
Restart embedded Cuckoo on crash

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV#36]
Currently Peekaboo dies/shuts down if the embedded Cuckoo child dies. With PR #35 merged we could look into trying to recover from that by restarting.

Things to consider:
- Now that we also have a REST API mode, should we spend effort on that or rather improve API support?
- How often do we try to restart Cuckoo at what intervals?
- What do we need to improve on the queueing/worker side to bridge the time until Cuckoo is restarted and accepting samples again. In the simplest case we could just have the submit retry a number of times with a waiting period and overall timeout, blocking their worker until successful or giving up.

**Comment by Jack28** [comment]
Embed mode is a legacy and will not receive any attention
