### ISSUE TITLE
SMIME signature exception does not seem to work

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV#39]
We need to retest if our SMIME attachment exception to avoid false positives actually works. There have been reports that it doesn't.

**Comment by michaelweiser** [comment]
@jack28: Do you perhaps have a test case (email) floating around that should trigger the problem?

**Comment by Jack28** [comment]
#96 solves this

**Comment by Jack28** [comment]
smime attachments are also `smime.p7m`

I propose a change to the rule to:
<code>
sample.meta_info_name_declared == 'smime.p7[sm]'
</code>
