### ISSUE TITLE
Add GPG signature exception

### ISSUE THREAD

**Issue by michaelweiser** [scVENUS/PeekabooAV#40]
We need to add an exception for GPG signatures similar to S/MIME (#39) to avoid false positivies.

Suggested by @Jack28.

**Comment by michaelweiser** [comment]
@jack28: Can you provide a test case (email with GPG attachment) that reproduces the problem?

**Comment by Jack28** [comment]
Extracted from peekaboo log for the atteched message:
[GPG Signed Message.zip](https://github.com/scVENUS/PeekabooAV/files/2548501/GPG.Signed.Message.zip)

`Sample declared as "application/pgp-signature"`

`Determined MIME Types: set([u'application/pgp-signature', 'text/plain'])`

`Adding rule result Ergebnis "unknown" der Regel file_type_on_greylist:97 - Dateityp ist nicht auf der Liste der zu analysierenden Typen (set([u'application/pgp-signature', 'text/plain'])), Analyse wird fortgesetzt: Nein.`

`Message send: Die Datei "p002" wurde als "unknown" eingestuft`

There is no analysis performed for this attachment
