### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#5]
Hi,

I've got a problem with starting the peekaboo.service. Systemctl starts the service and creates the peekaboo.sock. Even though after a few seconds the socket disappears und the service changes from active to activating...
Here's the error. I hope you could maybe help me.

> Nov 10 13:31:41 host.example.com systemd[1]: Starting Peekaboo Extended Email Attachment Behavior Observation Owl...
Nov 10 13:31:41 host.example.com python[4391]: Starting Peekaboo 1.3.
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,810 - peekaboo.daemon - (MainThread) - DEBUG - <PeekabooConfig({'db': {'url': 'postgresql://peekaboo:peekaboo@localhost:5432/peekaboo'}, 'global': {'job_hash_regex': '/var/lib/amavis/tmp/([^/]+)/parts.*', 'group': 'peekaboo', 'sample_base_dir': '/tmp', 'socket_file': '/opt/peekaboo/peekaboo.sock', 'worker_count': '3', 'use_debug_module': 'no', 'user': 'peekaboo', 'chown2me_exec': '/opt/peekaboo/bin/chown2me', 'pid_file': '/opt/peekaboo/peekaboo.pid', 'interpreter': '/usr/bin/python'}, 'logging': {'log_format': '%(asctime)s - %(name)s - (%(threadName)s) - %(levelname)s - %(message)s', 'log_level': 'DEBUG'}, 'cuckoo': {'storage_path': '/opt/cuckootest/storage', 'submit': '/usr/bin/cuckoo submit', 'exec': '/usr/bin/cuckoo'}})>
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,845 - peekaboo.db - (MainThread) - DEBUG - Cleared the database from "inProgress" entries.
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,845 - peekaboo.pjobs - (MainThread) - DEBUG - Create Worker 0
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,845 - peekaboo.pjobs - (Thread-1) - DEBUG - Worker is ready
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,845 - peekaboo.pjobs - (MainThread) - DEBUG - Create Worker 1
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,846 - peekaboo.pjobs - (Thread-2) - DEBUG - Worker is ready
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,846 - peekaboo.pjobs - (MainThread) - DEBUG - Create Worker 2
Nov 10 13:31:41 host.example.com python[4391]: 2017-11-10 13:31:41,846 - peekaboo.pjobs - (Thread-3) - DEBUG - Worker is ready
Nov 10 13:31:41 host.example.com python[4391]: Traceback (most recent call last):
Nov 10 13:31:41 host.example.com python[4391]:   File "/usr/bin/peekaboo", line 9, in <module>
Nov 10 13:31:41 host.example.com python[4391]:     load_entry_point('Peekaboo==1.3', 'console_scripts', 'peekaboo')()
Nov 10 13:31:41 host.example.com python[4391]:   File "build/bdist.linux-x86_64/egg/peekaboo/daemon.py", line 195, in run
Nov 10 13:31:41 host.example.com python[4391]:   File "build/bdist.linux-x86_64/egg/peekaboo/daemon.py", line 63, in __init__
Nov 10 13:31:41 host.example.com python[4391]:   File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__
Nov 10 13:31:41 host.example.com python[4391]:     self.server_bind()
Nov 10 13:31:41 host.example.com python[4391]:   File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
Nov 10 13:31:41 host.example.com python[4391]:     self.socket.bind(self.server_address)
Nov 10 13:31:41 host.example.com python[4391]:   File "/usr/lib64/python2.7/socket.py", line 228, in meth
Nov 10 13:31:41 host.example.com python[4391]:     return getattr(self._sock,name)(*args)
Nov 10 13:31:41 host.example.com python[4391]: socket.error: [Errno 98] Address already in use

regards, Michael

**Comment by Jack28** [comment]
I assume you use the systemd service file from PeekabooAV-Installer.
Please change your configuration file to use /var/run/peekaboo/ for PID and SOCKET file. That directory is managed by systemd.

best
Felix

**Comment by MigliS** [comment]
It didn't work like I expected. The same error occures again.

**Comment by Jack28** [comment]
These options should take care of removing the PID and SOCKET file located at /var/run/peekaboo/ :
RuntimeDirectory=peekaboo
RuntimeDirectoryMode=750

If you manually delete PID and SOCKET file does the error persist?
Please provide log, config and systemd unit file.
Which OS do you use?

**Comment by MigliS** [comment]
I'm using a Suse Linux Enterprise Server 12 SP2.
Your solution worked!
But now I'm getting a Permission denied on the peekaboo.sock.

> (!)connect to /var/run/peekaboo/peekaboo.sock failed, attempt #.1: Can't connect to a UNIX socket /var/run/peekaboo/peekaboo.sock: Permission denied

**Comment by MigliS** [comment]
Hi Felix,
I'm still having trouble with permissions, but I cannot figure out, where they come from...

**Comment by MigliS** [comment]
Okay. Problem solved!

**Comment by Jack28** [comment]
Congrats well done.
Please share your solution

**Comment by MigliS** [comment]
I'm running peekaboo just simply with this command:
``` peekaboo -c /opt/peekaboo/peekaboo.conf ```
And manually changes the permissions of the directory ``` /var/run/peekaboo ```
That's it! :sunglasses:

**Even though I can't see the cuckoo web interface. Is there any possibility to start it and see the results of each analysis?**

**Comment by Jack28** [comment]
`cuckohttpd.service` is part of the PeekabooAV-Installer. It allowes to have the Cuckoo web UI run as a service.
Have a look at it
