### ISSUE TITLE
Update of requirements.txt

### ISSUE THREAD

**Issue by Jack28** [scVENUS/PeekabooAV#51]
I have successfully tested with the following `requirements.tst`:
```
root@someubuntu:~/PeekabooAV-Installer/PeekabooAV# cat requirements.txt
sqlalchemy>=1.0.8
Twisted>=17.1.0
service_identity>=16.0.0
python-magic>=0.4.12
oletools>=0.51
sdnotify>=0.3.1
enum34>=1.0.4
yara-python>=3.6.3
requests>=2.19.1
```

Which results in the following installed versions:
```
root@someubuntu:~/PeekabooAV-Installer/PeekabooAV# pip list | grep -f <(sed 's/>.*//' requirements.txt )
enum34                             1.1.6
oletools                           0.51
python-magic                       0.4.12
requests                           2.13.0
sdnotify                           0.3.1
Twisted                            18.9.0
yara-python                        3.6.3
```

Please comment and/or update

**Comment by michaelweiser** [comment]
As it happens, I had this prepared exactly the same way already. Testing for problems/regressions now.

**Comment by michaelweiser** [comment]
I noticed that requests stays at 2.13.0 even though we require 2.19.1 exactly or greater. In my testing environment pip install -r requirements.txt throws:

```
cuckoo 2.0.6.2 has requirement chardet==2.3.0, but you'll have chardet 3.0.4 which is incompatible.
cuckoo 2.0.6.2 has requirement requests[security]==2.13.0; sys_platform == "linux2", but you'll have requests 2.20.1 which is incompatible.
```
Investigating.

**Comment by michaelweiser** [comment]
Cuckoo has pinned almost all of its dependencies as per https://github.com/cuckoosandbox/cuckoo/issues/602. At least requests and yara overlap. requests is pinned to a way older version by cuckoo than our minimum - which still seems to work though. Possible solutions:
- take pains to keep Peekaboo compatible to the same versions as (potentially various) Cuckoo versions
- install Cuckoo and Peekaboo in separate virtualenvs/pipenvs/... where they can have different module versions installed
- run them in Docker containers (REST API mode only)
- "We know what we're doing"-mode: Ignore Cuckoo (and perhaps Peekaboo) version requirements, e.g. by using Linux distribution packages and circumventing Cuckoo's setup.py and Peekaboo's requirements.txt.

**Comment by michaelweiser** [comment]
With scVENUS/Peekaboo-Installer#12 I now get the following versions:
```
PeekabooAV# /opt/peekaboo/bin/pip list | grep $(cut -d \> -f1 requirements.txt | tr '\n' '|' | sed -e "s,|$,,g" -e "s,|,\\\\|,g")
enum34           1.1.6     
oletools         0.53.1    
python-magic     0.4.15    
requests         2.20.1    
sdnotify         0.3.2     
Twisted          18.9.0    
yara-python      3.8.1     
```
Meanwhile, cuckoo uses those:
```
PeekabooAV# /opt/cuckoo/bin/pip list | grep $(cut -d \> -f1 requirements.txt | tr '\n' '|' | sed -e "s,|$,,g" -e "s,|,\\\\|,g")
enum34            1.1.6      
oletools          0.51       
python-magic      0.4.12     
requests          2.13.0     
yara-python       3.6.3      
```
