### ISSUE TITLE
Performace Testing

### ISSUE THREAD

**Issue by MigliS** [scVENUS/PeekabooAV#7]
Hi
I have a question about amavis & peekaboo processes.
On my server i'm running about 80 vm's. I configured $max_servers in amavisd.conf to 36. 

Is this correct or should I decrease this value?
How did you managed it?

regards, Michael

**Comment by Jack28** [comment]
I passed the question on the our on site mail expert and update as soon as I hear back from him.

**Comment by MigliS** [comment]
:smiley::thumbsup:

**Comment by Jack28** [comment]
Turns out the advise is to have a higher value for $max_servers than to have virtual machines. Since not every mail has an attachment that isn't known and needs to be analysed in a VM.
For 80 VMs you can easily set $max_servers to 100.

Thank Christoph vor that information.

**Comment by MigliS** [comment]
Thank you for your clarifications!
