### ISSUE TITLE
Update default evil sigs

### ISSUE THREAD

**Issue by Clevero** [scVENUS/PeekabooAV#95]
It would be easier if the pekaboo installer has a "regularly" updated list of evil sigs. That way also users that are no analysts could profit from higher detection rates.
In my opinion this would make peekaboo more likely a tool for other companies that "just" want to use peekaboo for their customers and maybe would result in higher usage

## Possible Solution
Have a thread where users can share their newly added and tested evil sig and are maybe added to the next peekaboo release if the false positive rate is not too high.

## Context (Environment)
The context of evil sigs are the ones that are also public available though the cuckoo community or in other ways are public available.

I recently tested peekaboo against older malware from our mail archive and needed to add "Connects to a Dynamic DNS Domain" in order to detect the malware.
I think that those who have more mail traffic to analyze and are monitoring the analysis results in order to detect false negatives have also other evil sigs that are currently not in the default list and others could benefit from it.

**Comment by Jack28** [comment]
I like that idea.

Lets make this a manual process for now. We can talk about the best and most reliable signatures over at https://gitter.im/PeekabooAV/Lobby and I'll regularly update the resulting config

**Comment by Jack28** [comment]
Which changes to the ruleset do you suggest, which additional rules, signatures ... ?

**Comment by Jack28** [comment]
You mentioned something about the `"Connects to a Dynamic DNS Domain"` signature.
How did it go, do you get good results by including it?

**Comment by Clevero** [comment]
Had some weeks where I sadly do not had the time to work on peekaboo/cuckoo.

Currently testing some rules, but I must admit that we do have significantly less traffic that probably you guys. To compensate that I started gathering an archive of malware listed at URLhaus to submit to peekaboo.
To have more "clean" files I'm going to try to collect an archive with files from archive.org and test against the added signatures


### Signatures that made no issues over two weeks but need more testing to be a default:
1. ```Connects to a Dynamic DNS Domain```

### Signatures that I think are worse enough and need less testing:
1. ```The process powershell.exe wrote an executable file to disk```
2. ```Creates a suspicious Powershell process```
3. ```Appends a new file extension or content to 1 files indicative of a ransomware file encryption process```
4. ```Creates a shortcut to an executable file```

### Signatures currently in testing:
1. ```Communicates with host for which no DNS query was performed```
2. ```Connects to IP addresses that are no longer responding to requests (legitimate services will remain up-and-running  usually)```
3. ```Word document hooks document open```
4. ```Word document hooks document close``` **definitely not sure about those two signatures. Could think about legit office documents with macros that prepare some stuff when opening**
